### ISSUE TITLE
POST/ GET request problem

### ISSUE THREAD

**Issue by lyndseysc** [FACxBeamery/Week3-toDoList-Thomas-Tom#15]
if i add an item via get request on postman it does not appear to be added to the list on the terminal 
<img width="717" alt="Screenshot 2019-09-27 at 11 01 57" src="https://user-images.githubusercontent.com/35724145/65761202-44202c00-e116-11e9-8f95-2da3c69b57dd.png">
<img width="423" alt="Screenshot 2019-09-27 at 10 57 21" src="https://user-images.githubusercontent.com/35724145/65761210-471b1c80-e116-11e9-96bb-23e843b78e2c.png">

**Comment by TKostrzewski** [comment]
Hi Lyndsey,

It may be the request method that's turning up the error. Could you see if it works with a POST request please?

Further down the line, we'll be restricting the request.method before we handle the request so using the wrong request method will divert you to a more descriptive error page.
