### ISSUE TITLE
Let's see some testing 👨🏻‍🔬

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/Week3-toDoList-Thomas-Tom#5]
You've got some great logic functions that you can test!

Tip: A pure function should not rely on any variables outside of its own scope - it looks like some of your logic functions use toDoList as a global variable - it's fine for your toDoList to be in the global scope, but you should pass it as an argument to any pure function you want to manipulate it with, then the function is independent of any state outside of itself and can be tested by passing in a set of dummy to-do-list data

**Comment by Oliversw** [comment]
You obviously saw this issue because you've managed to write some nice tests in a short time, congrats! I think the more that you can aim to write some (even very simple) tests as you go, the easier it will be moving forward 👏
