### ISSUE TITLE
Methods to concatenate arrays

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/Week3-toDoList-Thomas-Tom#6]
https://github.com/FACxBeamery/Week3-toDoList-Thomas-Tom/blob/a33ce1cffc4c4ed6606165ac1f1f76441e584cbc/src/handler.js#L23

A little test on the node REPL tells me that your output here might not be what you expected. Did you want to return two arrays within another array?

<img width="337" alt="Screen Shot 2019-09-27 at 09 54 55" src="https://user-images.githubusercontent.com/28838993/65756433-ff43c780-e10c-11e9-8160-bea80487d1b5.png">

Take a look at the `concat` array method. You could also flatten each array using the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

```
var parts = ['shoulders', 'knees']; 
var lyrics = ['head', ...parts, 'and', 'toes']; 
// ["head", "shoulders", "knees", "and", "toes"]
```

**Comment by thomas-galligan** [comment]
Thanks for raising this issue - we're thinking of keeping this structure for now as it means the two parts will be easy to extract (e.g. for filtering out incomplete items), but we'll bare it in mind!
